server:
  port: 8071
spring:
  profiles:
    active: git
  application:
    name: "configserver"
  cloud:
    config:
      server:
        git:
          clone-on-start: true
          uri: "https://github.com/Orozali/config-server-eazyBytes.git"
          default-label: main
          timeout: 5
          force-pull: true
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"

encrypt:
  key: "45D81EC1EF61DF9AD8D3E5BB397F9"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    liveness-state:
      enabled: true
    readiness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true